#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\SkillController::skillIndex

add_or_edit:
  path: /skills/{id}
  controller: App\Controller\SkillController::skillEdit

add_skill:
  path: /add_skill
  controller: App\Controller\SkillController::addEdit
